### ISSUE TITLE
Error reading a FITS table into a pandas DataFrame via astropy

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#1156]
I'm trying to read a FITS table into a pandas DataFrame via astropy.

Test data and script is here:
https://github.com/cdeil/test_fits_to_pandas

This is the error I get (same error from `read_via_table.py`):
```
$ python read_via_fits.py 
                                       nfev statname  numpoints
ROI                       Solution                             
HESS_J1023m575            4_big         273     cash      75000
                          5             316     cash      75000
                          3             131     cash      75000
                          4             273     cash      75000
                          2_elongated   111     cash      75000
ERROR: ValueError: Big-endian buffer not supported on little-endian compiler [unknown]
Traceback (most recent call last):
  File "read_via_fits.py", line 8, in <module>
    print(table[['nfev', 'statname']])
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/pandas-0.11.1.dev_cf47a42-py2.7-macosx-10.8-intel.egg/pandas/core/frame.py", line 2017, in __getitem__
    return self._getitem_array(key)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/pandas-0.11.1.dev_cf47a42-py2.7-macosx-10.8-intel.egg/pandas/core/frame.py", line 2054, in _getitem_array
    return self.take(indexer, axis=1, convert=True)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/pandas-0.11.1.dev_cf47a42-py2.7-macosx-10.8-intel.egg/pandas/core/frame.py", line 2998, in take
    return self.reindex(columns=new_columns)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/pandas-0.11.1.dev_cf47a42-py2.7-macosx-10.8-intel.egg/pandas/core/frame.py", line 2630, in reindex
    fill_value, limit)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/pandas-0.11.1.dev_cf47a42-py2.7-macosx-10.8-intel.egg/pandas/core/frame.py", line 2722, in _reindex_columns
    copy, fill_value)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/pandas-0.11.1.dev_cf47a42-py2.7-macosx-10.8-intel.egg/pandas/core/frame.py", line 2739, in _reindex_with_indexers
    fill_value=fill_value)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/pandas-0.11.1.dev_cf47a42-py2.7-macosx-10.8-intel.egg/pandas/core/internals.py", line 1959, in reindex_indexer
    return self._reindex_indexer_items(new_axis, indexer, fill_value)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/pandas-0.11.1.dev_cf47a42-py2.7-macosx-10.8-intel.egg/pandas/core/internals.py", line 1993, in _reindex_indexer_items
    allow_fill=False)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/pandas-0.11.1.dev_cf47a42-py2.7-macosx-10.8-intel.egg/pandas/core/common.py", line 540, in take_nd
    func(arr, indexer, out, fill_value)
  File "generated.pyx", line 2842, in pandas.algos.take_2d_axis0_int16_int16 (pandas/algos.c:69040)
ValueError: Big-endian buffer not supported on little-endian compiler
```

@iguananaut @astrofrog Am I doing something wrong (passing a `FITSrec` instead of a `recarray`)?
Is there a workaround?

**Comment by astrofrog** [comment]
It sounds like this will not be fixed by 1.0 so removing the milestone.

**Comment by rasmi** [comment]
Any updates on this, @embray? Maybe @jreback can chime in on the different approaches mentioned by you and @astrofrog.

**Comment by Cadair** [comment]
@astrofrog does your work in #3504 deal with this?

**Comment by astrofrog** [comment]
There are two issues here. The conversion from Table to DataFrame works ok with #3504:

```
>>> from astropy.table import Table
>>> t = Table.read('table.fits')
>>> df = t.to_pandas()
```

It is the next line that causes an error:

```
>>> df = df.set_index(['ROI', 'Solution'])
...
ValueError: Big-endian buffer not supported on little-endian compiler
```

```
df = df.set_index(['ROI', 'Solution'])
```

So weirdly, pandas is accepting the data regardless of endianness. I get the right result if I print out the DataFrame:


```
                         ROI     Solution  nfev statname  numpoints
0  HESS_J1023m575             4_big         273     cash      75000
1  HESS_J1023m575             5             316     cash      75000
2  HESS_J1023m575             3             131     cash      75000
3  HESS_J1023m575             4             273     cash      75000
4  HESS_J1023m575             2_elongated   111     cash      75000
5  HESS_J1713m397_RX1713_SNR  1              16     cash     116837
6  HESS_J1804m216             2             118     cash      97258
```

So somehow maybe it's just at the ``set_index`` phase that there is an endianness bug.

Either way, I find it weird that pandas would accept the data if it wasn't valid. So to me, there is definitely a bug in pandas, even if it's just that it should complain when big-endian data is first passed.

I am short on time but if someone else can investigate further this would be very helpful.

**Comment by embray** [comment]
There's a fair bit of code out there in SciPy, and I'm guessing Pandas as well, that assumes all the data it's going to get is little-endian, or at least doesn't bother to byteswap automatically where necessary.  So that wouldn't surprise me.

You'd actually be amazed by the amount of energy that has been put into debating whether or not FITS' big-endian requirement is harmful.  I and others argue that it is, some argue that it's a silly thing to worry about.  I think both sides have good points, but I'm quite devoted to my opinion on the matter and so are they.  (I feel though that the big-endian adherents just haven't had as much experience dealing with the real-world annoyances that arise as a result...)

**Comment by taldcroft** [comment]
By coincidence I just spent 20 minutes figuring out a big/little endian problem.  I read in a data array from a FITS file and send it to a CIAO plotting utility, which bonks.  I look at the array and it is what I expect.  Then I plot `array + 0` and it works fine.

Moral: these kind of errors are really devilish to track down if you aren't expecting it.  Have we ever had a serious discussion about having `Table.read(.., format='fits')` just convert to the native format by default?  Or what's the generic end-user way to handle this?

**Comment by astrofrog** [comment]
@taldcroft - no, we haven't had that discussion, and yes it might make sense to. While users likely want to preserve the precision type, e.g. ``i2``, ``i4``, ``i8``, ``f4``, ``f8``, etc., I can't think of a use case where keeping the original endianness is important. Even performance is not really an excuse because the endianness will have to be converted anyway if the array is to be used in any way.

**Comment by astrofrog** [comment]
We could also have a flag in ``Table`` e.g. ``preserve_endianness`` which defaults to ``False`` in case the user needs to manually override it.

**Comment by cdeil** [comment]
+1 to converting to native format by default!
(I think the number of users that will be bitten by this backwards-incompatible change will be very small compared to the number of users that will run into issues they don't understand because they got big-endian arrays.)

How do other packages (e.g. h5py, ....?) deal with this?

**Comment by taldcroft** [comment]
@astrofrog - I was also thinking that the endianness conversion could be isolated to `Table.read` while `io.fits` would still just give the values straight from the file (which would need to be the case for mem mapping).  So using `io.fits` directly would represent a path for the rare case of requiring the original endianness, so maybe `Table.read` just always does it as the "high-level" user-friendly interface.

But yeah, wrong endianness is really subtle and annoying to trace down.

**Comment by astrofrog** [comment]
@taldcroft - that sounds good to me. Now we could go one step further and build it in to ``Table`` (not ``Table.read``) so that users don't accidentally add columns with the wrong endian-ness, the idea being that we don't have to fix endian-ness on a per-format basis. We wouldn't fail if the user specifies an array with the wrong endian-ness, we'd just silently fix it. ``Table`` could also include an option in ``__init__`` that would be ``allow_non_native_endian`` defaulting to ``False``, or something similar.

**Comment by taldcroft** [comment]
@astrofrog sounds good to me!

**Comment by rasmi** [comment]
Makes sense. Would values have to be re-converted if data was being saved to a FITS file, or is that already built in?

**Comment by astrofrog** [comment]
If I'm understanding @embray correctly, all FITS data is stored in big endian? (so in that sense, yes the conversion back to big endian would be automatic when writing to a FITS file). Basically, everything would be seamless from the point of view of a user who doesn't care about endian-ness.

**Comment by mhvk** [comment]
:+1: to doing endian-conversion in the I/O parts (i.e., in `Table.read(...)`). However, :-1: to also do things as part of `Table` or `Column` -- that seems overkill since one already has to be pretty explicit to get the endianness wrong in non-I/O case.

**Comment by mwcraig** [comment]
:+1: to automatic conversion of some sort. Just got bit by this. Thanks to @taldcroft for the `+0` workaround!

**Comment by astrofrog** [comment]
Just for info, we've now merged https://github.com/astropy/astropy/pull/3504 which makes it easy to convert between astropy Tables and pandas DataFrame (and should deal properly with endian-ness)

**Comment by cdeil** [comment]
@astrofrog Thanks for implementing the Table / DataFrame converters.

I still see this error though ...
```python
>>> from astropy.table import Table
>>> table = Table.read('https://github.com/cdeil/test_fits_to_pandas/raw/master/table.fits')
>>> df = table.to_pandas()
>>> df[['nfev', 'statname']]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandas/core/frame.py", line 1781, in __getitem__
    return self._getitem_array(key)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandas/core/frame.py", line 1826, in _getitem_array
    return self.take(indexer, axis=1, convert=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandas/core/generic.py", line 1351, in take
    convert=True, verify=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandas/core/internals.py", line 3269, in take
    axis=axis, allow_dups=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandas/core/internals.py", line 3151, in reindex_indexer
    indexer, fill_tuple=(fill_value,))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandas/core/internals.py", line 3232, in _slice_take_blocks_ax0
    new_mgr_locs=mgr_locs, fill_tuple=None))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandas/core/internals.py", line 847, in take_nd
    allow_fill=False)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandas/core/common.py", line 823, in take_nd
    func(arr, indexer, out, fill_value)
  File "pandas/src/generated.pyx", line 2977, in pandas.algos.take_2d_axis0_int16_int16 (pandas/algos.c:86078)
ValueError: Big-endian buffer not supported on little-endian compiler
```

**Comment by astrofrog** [comment]
Oops, indeed I can reproduce that by adding a single line to a unit test

**Comment by astrofrog** [comment]
I actually think this is a pandas bug - if you access fields individually, it works fine. I've opened an issue in the panda repo: https://github.com/pydata/pandas/issues/9989

**Comment by astrofrog** [comment]
Ok so as recommended by the pandas dev, we should just flip the byte order ourselves if it's not native, though they are planning on trying to make that seamless in pandas because it's a common issue. So #3729 will fix that for Astropy.

**Comment by Andersonimpala** [comment]
> I'm working on some experimental custom dtype magic in Numpy that will allow data in non-native byte order to be "seen" as native by always byteswapping on demand when individual values are needed (such as going in and out of a ufunc, or simply displaying the data). This is actually what Numpy already does with data in non-native byte order--I'm just trying to make it a little more transparent. Slower? Yes, possibly. But it's a tradeoff. Still not 100% sure if it will work, but it might make for an interesting approach to this. Though it won't work with any code that tries to access the data buffer directly.





https://pythoner.space/questions/discover-the-prevailing-word-arrangement-within-a-pandas-data-table
