### ISSUE TITLE
Rethink how we publish What's New for a new release

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#13177]
@dhomeier reported broken links both in linkcheck and in the what's new listing for v5.1. We need to rethink the procedure for adding what's new during the period of a new release (between branching and final release) to avoid these problems.

1. `docs/whatsnew/5.1.rst.rst:3:broken link: https://docs.astropy.org/en/v5.1/whatsnew/5.1.html (404 Client Error: ...)`
2. https://docs.astropy.org/en/latest/whatsnew/ had "What’s New in Astropy 5.1?" pointing to https://docs.astropy.org/en/v5.0/whatsnew/5.1.html)https://docs.astropy.org/en/v5.0/whatsnew/5.1.html 

cc @astropy/astropy-project-release-team

**Comment by saimn** [comment]
Fixed the https://docs.astropy.org/en/v5.0/whatsnew/5.1.html url, should have been  https://docs.astropy.org/en/v5.1/whatsnew/5.1.html

**Comment by neutrinoceros** [comment]
just finding this. Was #16271 a duplicate of this issue (sort of) ?

**Comment by pllim** [comment]
Not really. Link check is still broken until we release v6.1. 

Example log: https://github.com/astropy/astropy/actions/runs/8874053687/job/24360846593

`broken    https://docs.astropy.org/en/v6.1.0/whatsnew/6.1.html - 404 Client Error: Not Found for url: https://docs.astropy.org/en/v6.1.0/whatsnew/6.1.html`

**Comment by Cadair** [comment]
The current state of main has the doc build failing: https://github.com/astropy/astropy/blob/9f55ef83be0f5059c22094df517f24722e9f3989/docs/whatsnew/7.0.rst?plain=1 / https://app.readthedocs.org/projects/astropy/builds/26091046/#248840604--1479 and I am lead to believe this is deliberate? This seems *insane* and is really frustrating.

Surely there must be any number of things we can do to make this not happen, like use a valid link, or use no link at all?

**Comment by pllim** [comment]
Update, breakage reported in https://github.com/astropy/astropy/issues/13177#issuecomment-2441762414 was fixed in #17262 but still, linkcheck would fail (with 1 error) until released is made.
