### ISSUE TITLE
Primary IERS A table has terminating null and crashing io.ascii parser

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#13223]
This is causing CI failures in this repo and downstream. cc @timj and @adonath 

Example log: https://github.com/astropy/astropy/runs/6312385715?check_suite_focus=true

```python
>>> from astropy.utils.data import download_file
>>> from astropy.utils.iers.iers import IERS_Auto
>>> url = 'https://maia.usno.navy.mil/ser7/finals2000A.all'
>>> filename = download_file(url, cache=False)  # Force download of latest copy
>>> t = IERS_Auto.read(file=filename)
```
```
.../astropy/utils/iers/iers.py in read(cls, file, readme)
    579             readme = IERS_A_README
    580
--> 581         iers_a = super().read(file, format='cds', readme=readme)
    582
    583         # Combine the A and B data for UT1-UTC and PM columns

.../astropy/table/connect.py in __call__(self, *args, **kwargs)
     60         descriptions = kwargs.pop('descriptions', None)
     61
---> 62         out = self.registry.read(cls, *args, **kwargs)
     63
     64         # For some readers (e.g., ascii.ecsv), the returned `out` class is not

.../astropy/io/registry/core.py in read(self, cls, format, cache, *args, **kwargs)
    210
    211             reader = self.get_reader(format, cls)
--> 212             data = reader(*args, **kwargs)
    213
    214             if not isinstance(data, cls):

.../astropy/io/ascii/connect.py in io_read(format, filename, **kwargs)
     16         format = re.sub(r'^ascii\.', '', format)
     17         kwargs['format'] = format
---> 18     return read(filename, **kwargs)
     19
     20

.../astropy/io/ascii/ui.py in read(table, guess, **kwargs)
    394         else:
    395             reader = get_reader(**new_kwargs)
--> 396             dat = reader.read(table)
    397             _read_trace.append({'kwargs': copy.deepcopy(new_kwargs),
    398                                 'Reader': reader.__class__,

.../astropy/io/ascii/cds.py in read(self, table)
    341                     return table
    342         else:
--> 343             return super().read(table)

.../astropy/io/ascii/core.py in read(self, table)
   1401                                      self.include_names, self.exclude_names)
   1402
-> 1403         table = self.outputter(self.header.cols, self.meta)
   1404         self.cols = self.header.cols
   1405

.../astropy/io/ascii/core.py in __call__(self, cols, meta)
   1137         # Sets col.data to numpy array and col.type to io.ascii Type class (e.g.
   1138         # FloatType) for each col.
-> 1139         self._convert_vals(cols)
   1140
   1141         t_cols = [numpy.ma.MaskedArray(x.data, mask=x.mask)

.../astropy/io/ascii/core.py in _convert_vals(self, cols)
   1080                 # If there are no converters left here then fail.
   1081                 if not col.converters:
-> 1082                     raise ValueError(f'Column {col.name} failed to convert: {last_err}')
   1083
   1084                 converter_func, converter_type = col.converters[0]

ValueError: Column year failed to convert: invalid literal for int() with base 10: '\x00\x00'
```

**Comment by pllim** [comment]
I have contacted USNO and will report back if they reply. 🤞

**Comment by ktlim** [comment]
For the record, here is a copy of the bad file with trailing nulls (slightly renamed).  [finals2000A-bad.all.txt](https://github.com/astropy/astropy/files/8641941/finals2000A-bad.all.txt)

**Comment by pllim** [comment]
Looks like this file has been fixed upstream because I no longer see the error when I download a fresh copy. I am removing the 🔥 label but will keep this issue open for now in case @taldcroft wants to investigate `io.ascii` parsing, otherwise feel free to close the issue. Thanks, all!

**Comment by Warren-Porter** [comment]
I am still getting the error (ValueError: Column year failed to convert: invalid literal for int() with base 10: '\x00\x00'), but it occurs when I attempt the conversion rather than when downloading the table.

I am using astropy version 5.0.4

Reproducible example:
from astropy.time import Time, TimeDelta
from astropy.utils import iers
dat = iers.IERS_A.open('https://maia.usno.navy.mil/ser7/finals2000A.all')
iers.IERS.iers_table = dat
(Time.now()-TimeDelta(3)).ut1 #Triggers ValueError due to null character

**Comment by pllim** [comment]
I just got a formal reply and turns out the file was corrupted, not just some extra characters. Therefore, I think we can close this issue without further investigation. It seems unrealistic to expect `io.ascii` to be successful on corrupted data. Below was the reply.

For those still getting error, please make sure you are not using a cached corrupted copy of the file be clearing the cache or force a re-download.

<hr/>

Thank you very much for reporting this. I've investigated the issue, and it appears that there was some problem with our automated upload process yesterday which caused finals2000A.data to become partially corrupted. Not only did the file end in multiple null characters, as you observed, but several lines of data were missing. I've reuploaded the file to ... and verified that it is now correct as it appears on the website. It should have the following MD5 checksum: 010e3d39264d65e4c7037c8f135f4440

Thanks again for bringing this to our attention. In the future, you can directly reach the group that publishes these files at our new group email address: eopcp@us.navy.mil

**Comment by Warren-Porter** [comment]
I still have difficulty when I force a redownload:
from astropy.utils.data import download_file
from astropy.time import Time, TimeDelta
from astropy.utils import iers
url = 'https://maia.usno.navy.mil/ser7/finals2000A.all'
filename = download_file(url, cache=False)  # Force download of latest copy
dat = iers.IERS_Auto.read(file=filename)
iers.IERS.iers_table = dat
iers.conf.auto_download = False
(Time.now()-TimeDelta(33)).ut1

**Comment by pllim** [comment]
@Warren-Porter , the error only crops up when you do the extra IERS table manipulation and I am not sure why. I think you should open a new issue. Here is what I see with `astropy` v5.1rc1

```python
>>> from astropy.utils.data import download_file
>>> from astropy.time import Time, TimeDelta
>>> from astropy.utils import iers
>>> url = 'https://maia.usno.navy.mil/ser7/finals2000A.all'
>>> filename = download_file(url, cache=False) # Force download of latest copy
Downloading https://maia.usno.navy.mil/ser7/finals2000A.all
...
>>> # Without further manipulation, I see a warning and somehow another download
>>> # but no error
>>> (Time.now()-TimeDelta(33)).ut1
WARNING: TimeDeltaMissingUnitWarning: Numerical value without unit or explicit format passed to TimeDelta, assuming days [astropy.time.core]
Downloading https://maia.usno.navy.mil/ser7/finals2000A.all
...
<Time object: scale='ut1' format='datetime' value=2022-04-03 17:52:50.231089>
```

With your code, I do see the following traceback:

```
.../astropy/time/core.py in __getattr__(self, attr)
   1383                 else:
   1384                     tm = self.replicate()
-> 1385                     tm._set_scale(attr)
   1386                     if tm.shape:
   1387                         # Prevent future modification of cached array-like object

.../astropy/time/core.py in _set_scale(self, scale)
    631                     pass
    632                 else:
--> 633                     args.append(get_dt(jd1, jd2))
    634                     break
    635

.../astropy/time/core.py in _get_delta_ut1_utc(self, jd1, jd2)
   2098                 scale = self.scale
   2099             # interpolate UT1-UTC in IERS table
-> 2100             delta = iers_table.ut1_utc(jd1, jd2)
   2101             # if we interpolated using UT1 jds, we may be off by one
   2102             # second near leap seconds (and very slightly off elsewhere)

.../astropy/utils/iers/iers.py in ut1_utc(self, jd1, jd2, return_status)
    300             ``iers.TIME_BEYOND_IERS_RANGE``
    301         """
--> 302         return self._interpolate(jd1, jd2, ['UT1_UTC'],
    303                                  self.ut1_utc_source if return_status else None)
    304

.../astropy/utils/iers/iers.py in _interpolate(self, jd1, jd2, columns, source)
    446             return results
    447         else:
--> 448             self._check_interpolate_indices(i1, i, np.max(mjd))
    449             return results[0] if len(results) == 1 else results
    450

.../astropy/utils/iers/iers.py in _check_interpolate_indices(self, indices_orig, indices_clipped, max_input_mjd)
    381                        'Astropy configuration system documentation '
    382                        'https://docs.astropy.org/en/stable/config/index.html.')
--> 383                 raise IERSRangeError(msg)
    384             elif conf.iers_degraded_accuracy == 'warn':
    385                 # No IERS data covering the time(s) and user requested a warning.

IERSRangeError: (some) times are outside of range covered by IERS table. Cannot convert with full accuracy.
To allow conversion with degraded accuracy set astropy.utils.iers.conf.iers_degraded_accuracy to "warn" or "silent".
For more information about setting this configuration parameter or controlling its value globally,
see the Astropy configuration system documentation https://docs.astropy.org/en/stable/config/index.html.
```

🤷
