### ISSUE TITLE
ValueError when vstacking tables with vector columns

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3877]
As reported by Brian Cherinka on the mailing list. Minimal example:

```python
import numpy as np
from astropy.table import Table, vstack

dt1 = np.dtype([('a', float)])
dt2 = np.dtype([('b', '<f8', (7,))])

data1 = np.zeros(10, dtype=dt1)
data2 = np.zeros(10, dtype=dt2)

t1 = Table(data1)
t2 = Table(data2)

t3 = vstack([t1, t2], join_type='outer')

print(t3[0])
```

gives

```
Traceback (most recent call last):
  File "debug_vstack.py", line 16, in <module>
    print(t3[0])
  File "/Users/tom/miniconda3/envs/production27/lib/python2.7/site-packages/astropy/table/row.py", line 178, in __repr__
    self.index, self.as_void(), self.dtype, self.__class__.__name__)
  File "/Users/tom/miniconda3/envs/production27/lib/python2.7/site-packages/numpy/ma/core.py", line 5701, in __repr__
    if not any(m):
  File "/Users/tom/miniconda3/envs/production27/lib/python2.7/site-packages/numpy/ma/core.py", line 6091, in __call__
    return method(MaskedArray(a), *args, **params)
  File "/Users/tom/miniconda3/envs/production27/lib/python2.7/site-packages/numpy/ma/core.py", line 2651, in __new__
    _data = np.array(data, dtype=dtype, copy=copy, subok=True, ndmin=ndmin)
ValueError: setting an array element with a sequence.
```

**Comment by astrofrog** [comment]
I think this is just related to masking and multi-dimensional columns, not vstack specifically. Another example of failure:

```
In [41]: t = Table(masked=True)

In [42]: t['a'] = np.ma.array([[1,2,3],[4,5,6]], mask=[[0,1,0],[1,0,1]])

In [43]: t[0]
Out[43]: ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/IPython/core/formatters.py in __call__(self, obj)
    688                 type_pprinters=self.type_printers,
    689                 deferred_pprinters=self.deferred_printers)
--> 690             printer.pretty(obj)
    691             printer.flush()
    692             return stream.getvalue()

/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    405                             if callable(meth):
    406                                 return meth(obj, self, cycle)
--> 407             return _default_pprint(obj, self, cycle)
    408         finally:
    409             self.end_group()

/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/IPython/lib/pretty.py in _default_pprint(obj, p, cycle)
    525     if _safe_getattr(klass, '__repr__', None) not in _baseclass_reprs:
    526         # A user-provided repr. Find newlines and replace them with p.break_()
--> 527         _repr_pprint(obj, p, cycle)
    528         return
    529     p.begin_group(1, '<')

/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    707     """A pprint that just redirects to the normal repr function."""
    708     # Find newlines and replace them with p.break_()
--> 709     output = repr(obj)
    710     for idx,output_line in enumerate(output.splitlines()):
    711         if idx:

/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/astropy/table/row.py in __repr__(self)
    176     def __repr__(self):
    177         return "<{3} {0} of table\n values={1!r}\n dtype={2}>".format(
--> 178             self.index, self.as_void(), self.dtype, self.__class__.__name__)
    179 
    180 

/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/numpy/ma/core.py in __repr__(self)
   5705             return self.filled(self.fill_value).__repr__()
   5706         p = str(p)
-> 5707         r = [(str(_), p)[int(_m)] for (_, _m) in zip(self._data.tolist(), m)]
   5708         return "(%s)" % ", ".join(r)
   5709 

/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/numpy/ma/core.py in <listcomp>(.0)
   5705             return self.filled(self.fill_value).__repr__()
   5706         p = str(p)
-> 5707         r = [(str(_), p)[int(_m)] for (_, _m) in zip(self._data.tolist(), m)]
   5708         return "(%s)" % ", ".join(r)
   5709 

TypeError: only length-1 arrays can be converted to Python scalars
```

**Comment by astrofrog** [comment]
@taldcroft - would you have time to look into this?

**Comment by taldcroft** [comment]
@astrofrog - yes

**Comment by taldcroft** [comment]
This is an upstream bug in np.ma, where the repr of a multi-d row fails.  The astropy Row call to `self.as_void` converts the row to a numpy masked array void object in order to let `np.ma` do the actual array values repr. 
```
In [33]: t_ma = np.ma.masked_array(data = [([1, 2, 3],)],
             mask = [([False, True, False],)],
       fill_value = ([999999, 999999, 999999],),
            dtype = [('a', '<i8', (3,))])

In [34]: print(t_ma[0])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-34-454d85211b19> in <module>()
----> 1 print(t_ma[0])

/Users/aldcroft/anaconda/envs/astropy/lib/python2.7/site-packages/numpy/ma/core.pyc in __str__(self)
   5691         else:
   5692             p = str(p)
-> 5693         r = [(str(_), p)[int(_m)] for (_, _m) in zip(r, m)]
   5694         return "(%s)" % ", ".join(r)
   5695 

TypeError: only length-1 arrays can be converted to Python scalars

In [35]: t_ma = np.ma.masked_array(data = [([1, 2, 3],)],
             mask = [([False, False, False],)],
       fill_value = ([999999, 999999, 999999],),
            dtype = [('a', '<i8', (3,))])

In [36]: print(t_ma[0])
([1, 2, 3],)
```
It has been said that astropy are becoming the defacto maintainers of numpy.ma.  :smile:  Anyway I'll put this up on numpy issues.

**Comment by mhvk** [comment]
@taldcroft - might this be fixed in numpy master (e.g., because of https://github.com/numpy/numpy/pull/4576)

**Comment by astrofrog** [comment]
@mhvk - just tried, but it doesn't seem to fix it on my side

**Comment by embray** [comment]
They weren't kidding when they said we're the de-facto maintainers of `np.ma` now.

**Comment by pllim** [comment]
:scream:

**Comment by astrofrog** [comment]
@taldcroft - just to check, did you open an issue on the numpy repository?

**Comment by taldcroft** [comment]
@astrofrog - https://github.com/numpy/numpy/issues/6019

**Comment by astrofrog** [comment]
This will be fixed in https://github.com/numpy/numpy/pull/6094 - unfortunately it didn't make the 1.10 cut, but will hopefully make the next bug-fix release

**Comment by taldcroft** [comment]
Since this is marked Upstream Fix Required, could this issue be closed by adding a Known Issue?  Otherwise this will sit open until at least numpy 1.11.

**Comment by astrofrog** [comment]
@taldcroft - how about we close it when the Numpy PR is merged?

**Comment by taldcroft** [comment]
OK.

**Comment by astrofrog** [comment]
numpy/numpy#6094 has been merged, and I can confirm that the Astropy example above now runs, so closing this issue. Don't think we can add a workaround without creating our own masked array subclass,  and it's not a critical bug since the issue is just with the printing/string conversion. An easy workaround is to simply do

```
print(t3[0:1])
```

instead of

```
print(t3[0])
```
