### ISSUE TITLE
Tests fail for version 1.3.dev15936

### ISSUE THREAD

**Issue by maroba** [astropy/astropy#5223]
Running the test suite as described in http://docs.astropy.org/en/latest/development/workflow/get_devel_version.html#test-installation
 gives me a number of failed tests, see output in attached file.

[testsuite_output.txt](https://github.com/astropy/astropy/files/406318/testsuite_output.txt)

**Comment by astrofrog** [comment]
@maroba - can you confirm how you ran the tests?

It looks like you are using non-stable versions of Numpy (1.8.0rc1) and SciPy (0.13.0b1) - how did you install these? (I just want to make sure it's not a bug that was fixed in the proper version of Numpy)

**Comment by maroba** [comment]
It seems I had two versions of numpy/scipy where the older versions shadowed the newer ones. This should be fixed now. However, the tests still fail. New output is attached.

[testsuite_output.txt](https://github.com/astropy/astropy/files/406903/testsuite_output.txt)

**Comment by pllim** [comment]
I'm a bit confused. 1.3 is not even released yet. How is Astropy version reporting 1.3.devXXXX? Did I miss a release?

**Comment by MSeifert04** [comment]
@pllim The current master has 1.3dev (https://github.com/astropy/astropy/blob/master/setup.py#L26)

**Comment by astrofrog** [comment]
We normally use next_version.dev for development versions :)

**Comment by pllim** [comment]
Oh... The last I synced, it was still reporting 1.2. :sweat_smile:  Sorry for he noise.

**Comment by astrofrog** [comment]
@pllim - yes, that was an oversight on my part!

**Comment by bsipocz** [comment]
@pllim - I had that problem recently, too, but running ``python setup.py develop`` fixed it.

**Comment by pllim** [comment]
I cannot reproduce the reported failure on my machine with the same dev version. However, I did find some remote data failures (which are unrelated to this issue) and reported them at #5224.

**Comment by pllim** [comment]
@maroba , is still a problem with latest dev?

**Comment by maroba** [comment]
No more fails, just skips and xfails. However, I changed my system in the meantime, so I'm not sure if the problems would persist in the old environment.
