### ISSUE TITLE
Creating new dB units fail with `def_unit`

### ISSUE THREAD

**Issue by dhicksNTIA** [astropy/astropy#5945]
In your documentation, you demonstrate that a new Unit definition can be made as such:
`>>> kmph = u.def_unit('kmph', u.km / u.h)`

So, I tried something similar: 
`In [2]: a = units.def_unit('dBW', units.dB(units.W))`

However, instead of making a new units, I received this error instead:
```
ValueError                                Traceback (most recent call last)
<ipython-input-28-90e4cc6e9112> in <module>()
----> 1 a = units.def_unit('dBW', units.dB(units.W))

***/python2.7/site-packages/astropy/units/core.pyc in def_unit(s, represents, doc,
format, prefixes, exclude_prefixes, namespace)
   2290     if represents is not None:
   2291         result = Unit(s, represents, namespace=namespace, doc=doc,
-> 2292                       format=format)
   2293     else:
   2294         result = IrreducibleUnit(

***/python2.7/site-packages/astropy/units/core.pyc in __call__(self, s, represents,
 format, namespace, doc, parse_strict)
   1834                            .format(s, format_clause, six.text_type(e)))
   1835                     if parse_strict == 'raise':
-> 1836                         raise ValueError(msg)
   1837                     elif parse_strict == 'warn':
   1838                         warnings.warn(msg, UnitsWarning)

ValueError: 'dBW' did not parse as unit: At col 0, dBW is not a valid unit. Did you mean dB, dW or db?
```

This is probably a bug that should be fixed.

**Comment by mirca** [comment]
Looks like the bug is due to (?):

```
>>> isinstance(u.dB(u.W), u.UnitBase)
False
>>> isinstance(u.m / u.s, u.UnitBase)
True
```

**Comment by dhicksNTIA** [comment]
@mirca Ohhhhh. Man, I am dumb. Thank you! I'll delete this.

**Comment by mirca** [comment]
@dhicksNTIA Well, actually, I would leave this open because we want to hear from the ``units`` maintainers =)

**Comment by mirca** [comment]
cc @mhvk

**Comment by mhvk** [comment]
@dhicksNTIA - thanks for reporting, and, yes, definitely keep this open! I don't have an instant answer, as it needs a bit of thought whether `def_unit` should be adapted or a new `def_function_unit` created. I'd tend to the former, in which case this is a bug. But even for the latter, we should at least document this!

Separately, I'm not quite sure what your use case is, but I found that `def_unit` was most useful if one wants the unit to be available in the namespace (to find equivalent units, etc.). For many purposes, it suffices to just do
```
dBW = units.dB(units.W)
```
and then use `dBW` whenever you need the unit.

**Comment by dhicksNTIA** [comment]
@mhvk Thanks! Yeah, I think the former is better too. 

My use case is reading a JSON file filled with items and their units. I already do this:
`units.dBW = units.dB(units.W)`
So that I can just use `getattr(units, 'dBW')` when reading the JSON file. However, now I need to handle compound units like milliSiemens per second (i.e. `units.milliSiemens / units.second`) and I cannot do `getattr(units, 'milliSiemens / second')`.

It would just be nice to do this:
`units.def_unit(['dBW', 'decibel-Watt'], units.dB(units.W), namespace=units)`
That way I can do this:
```
a = 10 * units.Unit('decibel-Watt')
b = 5 * units.Unit('milliSiemens / second')
c = 2 * units.Unit('dBW')
```

**Comment by mhvk** [comment]
Yes, that makes a lot of sense. It is not a trivial fix, though, since the `Unit` constructor has to become aware of function units, and it looks like I would need a `NamedFunctionUnit` class. This goes back to really wanting more abstract units and quantity classes (#3650), so that one could more easily combine a "being named" property with different types of units.

Anyway, this may be a little bit (unless you feel so inclined, but as said, this is not trivial). In the meantime, please do keep raising issues if you encounter other things that you think should work!

**Comment by nstarman** [comment]
This is now fixed! Probably has been for years.

![CleanShot 2024-12-04 at 19 32 26@2x](https://github.com/user-attachments/assets/3b3c10fa-24f3-413f-9c27-3b55064fcf40)

**Comment by mhvk** [comment]
The problem remains that we do not have a `NamedFunctionUnit(FunctionUnitBase)` (or that `NamedUnit` assumes that what it represents is a regular unit); https://github.com/astropy/astropy/issues/5945#issuecomment-292019634

**Comment by pllim** [comment]
> in a way it is worse than before

Uh oh... should we at least document this in https://docs.astropy.org/en/latest/known_issues.html until a solution is found?

**Comment by neutrinoceros** [comment]
I wanted to check when the change was introduced and bisected it down to 73232e8b62887ce9cb7139a1a4edd64d10568fac from #17399 (unreleased), so we have the option of reverting that PR before we decide to call it a known issue.
Ping @eerovaher

**Comment by pllim** [comment]
So, do we want to get it back to the point where the OP use case throws exception again? Should probably add that as a test, just in case.

**Comment by neutrinoceros** [comment]
Yes, and yes. Having a test for a known issue feels messy in principle *but* practically this appears to be needed.

**Comment by eerovaher** [comment]
It's not obvious to me that we have a problem here. My impression from reading the code is that `Unit` is meant to be a wrapper for whatever is contained in its `represents` attribute and the `Unit` instance that is created by e.g. `def_unit("dBW", u.dB(u.W))` does have a `represents` attribute that does contain the `DecibelUnit` instance.

**Comment by mhvk** [comment]
It does give something that is useless and thus unexpected, in that one cannot create a quantity by multiplying by it; see https://github.com/astropy/astropy/issues/5945#issuecomment-2520637457

But I think that it is sufficiently useless that we do not need any reversion or so -- adding a known issue seems the best path forward. The nice by-product is that it creates a test case too, since our doctests include the known issues page.

**Comment by pllim** [comment]
Please see https://github.com/astropy/astropy/pull/17551 for the "known issue" doc addition. Thanks!
