### ISSUE TITLE
Support selecting multiple column names in FITS_rec

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#6820]
`FITS_rec` behaves like a Numpy structured array, but doesn't support selecting multiple column names (tested with Numpy 1.13 and both Astropy 2.0.2 and master). See the example here:
https://gist.github.com/4f3d0684183da6f413539854f213b845

The workaround I'm using right now is:
```python
data = fits.getdata('/path/to/file.fits')
data = data.view(data.dtype, np.ndarray)
```

**Comment by pllim** [comment]
@adrn , has this been solved with Unified I/O using `Table`?

**Comment by adrn** [comment]
This specific issue is still present with `FITS_rec`. 

This might still be a relevant feature request: I believe `Table` loads all data into memory (?), whereas `FITS_rec` could in principle work with `mmap=True`, and then selecting just a few column names would be more memory efficient. But I could be wrong about memmap...

**Comment by pllim** [comment]
I thought Table added `memmap` at some point but I don't remember the details. @saimn mentioned that this is not trivial to implement in `io.fits`.

**Comment by saimn** [comment]
You can use memmap with `Table` now, e.g. `Table.read(..., memmap=True)`.
However this is interesting when reading rows, for columns I guess it will still load the whole file.

**Comment by embray** [comment]
It depends on the format of the table.  For tables with only a few columns, selecting one column will typically mean loading the whole table into memory anyways since the strides will be less than one page size.  For tables with many large columns, you can get some savings, depending on the stride size.

These are things that IIRC [fitsio](https://pypi.org/project/fitsio/) handles better anyways, because it read an entire column (not sure about multiple columns simultaneously) without mapping the entire file into memory.

To be clear, though, if you take a view of a table consisting of one or a few columns it's not like it will be paged into memory all at once either--only as parts of the table are accessed.

**Comment by embray** [comment]
The lack of support for selecting multiple column names simultaneously seems to just be a minor interface issue.  I forgot you could even do that with Numpy structured arrays (is it a new feature for parity with Pandas or has it always been there?)
