### ISSUE TITLE
Appveyor testing stopped 3 days ago

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#6996]
Something must have happened recently, and we better figure this out soon.

**Comment by bsipocz** [comment]
Clicking on "New build" gives the following error:
```
Cannot read last commit information from GitHub repository astropy/astropy: HTTP GET to https://api.github.com/repos/astropy/astropy/branches/master returned status code 401: Unauthorized Full response body: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
```

**Comment by pllim** [comment]
FWIW here is a potential solution (the cause was different, but same error code) -- https://help.appveyor.com/discussions/questions/3935-status-code-401-unauthorized

**Comment by bsipocz** [comment]
Hopefully it indeed being fixed by redoing the authentication. There is a slight chance though that I messed it up as it was done from under my account and not a generic astropy org one, but currently everything seems to back in normal.

Many thanks @pllim for digging the solution up!

**Comment by eteq** [comment]
FWIW, I still see it all hooked up as before when logged in as me, so I think that means we're in the clear, @bsipocz ?

**Comment by bsipocz** [comment]
Yes, I hope so, appveyor just has a weird and confusing authentication structure (it asked for permission to access my, bsipocz, repository, etc github data, but then reauthenticated the astropy org's webhooks). (http://help.appveyor.com/discussions/problems/10346-appveyor-stopped-working-for-our-open-source-project#comment_44315034)
