### ISSUE TITLE
Astropy modeling memory leak -- problem with models with large arrays

### ISSUE THREAD

**Issue by followthesheep** [astropy/astropy#8479]
In astropy versions > 1, the modeling framework appears to deep copy models when they are concatenated. In version 1, I think it uses a reference. This makes a very big difference when the models contain very large arrays. I'm using a spectral fitting library which contains a large grid as part of the model (https://github.com/starkit/starkit). We use the astropy modeling framework to concatenate multiple operations on the spectrum before fitting such as rotation and radial velocity shifts. This requires concatenating multiple operations onto the original model. These operations now take a very long time because the grid gets copied for every operation (I think). Previously, it was basically instantaneous. 

The bigger problem is that when fitting multiple spectra, and re-creating the model, the memory is not released so my computer quickly runs out of ram. Even using the 'del' command does not release the memory on the variable. 

I'm not sure how to deal with this issue. Right now, we are unable to use any astropy version past 1. Is there a way to not deepcopy the models?

**Comment by pllim** [comment]
@nden or @perrygreenfield ?

**Comment by nden** [comment]
- Regarding the deep copy of models in a compound model - this is a stop gap measure to address a flaw in the current design where updates to the parameters of the compound model did not propagate to the parameters of the constituent models causing a compound model to be evaluated with the wrong parameters in some cases. The `CompoundModel` was rewritten to avoid this problem though it was decided the new code will go on astropy v4, some time by the end of the year, in order to have a deprecatioon period for the current implementation.

- Regarding the fitting problem - which version of astropy are you running? A related issue was fixed in #8349 and released with astropy 3.1.2. I wonder if it fixes th efitting issue you are reporting.

**Comment by followthesheep** [comment]
@nden The version we used with starkit that had this problem was astropy 3.1.2

Is there a beta version of astropy v4 we can try?

**Comment by bsipocz** [comment]
@followthesheep - The next release of astropy will be 3.2, that's what you get when trying the master branch. v4.0 is scheduled to come out ~half a year after that, next autumn.

It's also possible to install development versions from feature branches, but the one you are looking for is currently work in progress.

**Comment by LucIJspeert** [comment]
I think I might be experiencing the same or a related problem - one that fills up the memory very quickly (see image: timescale ~60 seconds, 16 GB full). 

I am doing PSF photometry from photutils, and it seems to be happening right when it runs the fitting with `LevMarLSQFitter` form astropy. I think the traceback from when I killed the process (right on time when the memory was full) confirms this; there is a mention of astropy\modeling\core.py and then a whole lot of occurances of `deepcopy`. It's quite a long list so I'll not post it as long as it is not needed.

Is there any workaround that I can use now - before the update rolls out that is supposed to fix this properly? For example I wouldn't mind breaking my local install of astropy to get this photometry working 😅

![IMG-20190517-WA0000](https://user-images.githubusercontent.com/46969344/57948127-1cf05d00-78e1-11e9-9b11-f7bcd5c8bac1.jpeg)

**Comment by saimn** [comment]
@LucIJspeert - This is probably the issue that was fixed in #8349. If possible can you try with the release candidate version for 3.2 ? (`pip install astropy==3.2rc1`)

**Comment by LucIJspeert** [comment]
@saimn Thanks for the suggestion and your quick response. Unfortunately it did not fix the issue. 
It did give me the deprecation warning for `CompoundModel`:
`AstropyDeprecationWarning: Composition of model classes will be removed in 4.0(but composition of model instances is not affected)`
But the memory still quickly filled up.

**Comment by pllim** [comment]
@LucIJspeert , can you please provide a code snippet? If you get that warning, you might be using it in a way that we don't plan to support anymore.

**Comment by LucIJspeert** [comment]
@pllim of course:

```Python
import photutils as phu
import astropy as apy
import astropy.modeling as apm

sigma_to_fwhm = apy.stats.gaussian_sigma_to_fwhm
bkgrms = phu.background.MADStdBackgroundRMS()
std = bkgrms.calc_background_rms(data=img_data)
fwhm = 5.0
daofind = phu.detection.DAOStarFinder(threshold=5*std,
                                      fwhm=fwhm,
                                      sigma_radius=0.8*fwhm*apy.stats.gaussian_fwhm_to_sigma,
                                      roundhi=10.0, roundlo=-10.0,
                                      sharplo=0.0, sharphi=20.0)
found = daofind(img_data)
found.rename_column('xcentroid', 'x_0')
found.rename_column('ycentroid', 'y_0')

mmmbkg = phu.background.MMMBackground()
daogroup = phu.psf.DAOGroup(crit_separation=5.0*fwhm)
lmfitter = asm.fitting.LevMarLSQFitter()
photometry = phu.psf.BasicPSFPhotometry(group_maker=daogroup, bkg_estimator=mmmbkg, 
                                        psf_model=epsf, fitshape=191, finder=None, 
                                        fitter=lmfitter, aperture_radius=fwhm)
result_tab = photometry(image=img_data, init_guesses=found)
residual_image = photometry.get_residual_image()
```

It seems to work up until running the photometry to get the result_tab.

**Comment by pllim** [comment]
@larrybradley or @eteq , do you know what is it `photutils` that might trigger this below?

https://github.com/astropy/astropy/blob/b8fddb2fc8fc7bf5c3c2367a836b2a4db8937163/astropy/modeling/core.py#L71-L77

You are not composing from model *classes*, right? Only *instances* should be used.

**Comment by LucIJspeert** [comment]
@pllim Perhaps that traceback helps find what triggers that 
```
  File "<local_dir>\photutils\psf\photometry.py", line 187, in __call__
    return self.do_photometry(image, init_guesses)
  File "<local_dir>\photutils\psf\photometry.py", line 290, in do_photometry
    output_tab, self._residual_image = self.nstar(image, star_groups)
  File "<local_dir>\photutils\psf\photometry.py", line 340, in nstar
    self._pars_to_set)
  File "<local_dir>\photutils\psf\utils.py", line 141, in get_grouped_psf_model
    group_psf += psf_to_add
  File "<local_dir>\astropy\modeling\core.py", line 80, in _opfunc
    return _CompoundModelMeta._from_operator(oper, left, right, **kwargs)
  File "<local_dir>\astropy\modeling\core.py", line 2433, in _from_operator
    children.append(copy.deepcopy(child._tree))
  File "<local_dir>\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "<local_dir>\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "<local_dir>\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "<local_dir>\lib\copy.py", line 240, in _deepcopy_dict
```
Those last four lines with `deepcopy` keep repeating after this, until memory is full.

**Comment by larrybradley** [comment]
@pllim PSF fitting combines model instances (the input `psf_model` is an instance).  There was only one case of combining model classes in `photutils`, but that was in the `centroid_2dg` function (fixed in https://github.com/astropy/photutils/pull/824/files).

**Comment by nden** [comment]
@LucIJspeert Do you know how many models you are combining when it fails? And what os are you running this on?

**Comment by LucIJspeert** [comment]
@nden Judging from the crowdedness in my images and my crit_sep parameter, I think the group size is around 5, up to a few dozen perhaps. 
I'm running it in an IDE on windows, but I could try it on Ubuntu, if that might help 😅

**Comment by pllim** [comment]
@LucIJspeert , what about trying to use `memory_profiler` and see? (Sorry if you already did that, but I can't seem to see a result of that by glancing over the conversation above.)

**Comment by nden** [comment]
@LucIJspeert The number of models is not big enough to trigger a memory error. I wonder if something else if causing it. Can you share your data?

**Comment by LucIJspeert** [comment]
@pllim I can't seem to get an output from `memory_profiler` so quickly - I'm probably not using it right... I'll have a better look at that.

@nden by data I suppose you mean the .fits image I'm trying to analyse? The file seems to be too large (>10 MB, even compressed) to attach it unfortunately, maybe through some other way? 
Coming back to my statement: I largely underestimated the largest group size, sorry about that. I quantified it, and while most are small, the largest group has over 2000 members. This does decrease a lot when I use a smaller `crit_separation`, but that is when the group-psfs will still be overlapping with neighbouring groups, and the fit will likely not be very good. 
The number of groups also goes up then, and I think the code might not be very efficient with large numbers of groups, because the photometry (just one iteration) takes very very long when I basically don't group any of the stars (with a tiny `crit_separation`). Although it does produce an output eventually, which is better than nothing I guess ;)

Perhaps I should find the midway between good fitting and full memory :P

**Comment by nden** [comment]
@LucIJspeert @followthesheep It would be great if you can run your tests with the current astropy master and report if the memory issues are fixed. #8769 included a substantial refactoring of modeling. One of the changes is that `CompoundModel` initialization does not make copies of constituent models and memory usage should be highly reduced.

**Comment by LucIJspeert** [comment]
@nden A problem occurred when trying to install astropy master: I downloaded the master branch and did `pip install astropy-master.zip`. This seemed to work until it ended with the message `error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/` and reverted back to my previous astropy install. I am quite certain that Microsoft Visual C++ 14.0 is installed on my system, since I have gotten this error before. Is there something I do wrong here or is there some way around this? I would like to test if the memory bug is gone.

![image](https://user-images.githubusercontent.com/46969344/62287073-6587d300-b459-11e9-880a-230599ecf221.png)

**Comment by nden** [comment]
@bsipocz Any idea how to solve the above problem ⬆️?

**Comment by pllim** [comment]
@LucIJspeert , unfortunately, it is not `astropy` problem, but rather your Python cannot "see" your MSVC compiler. Depending on how your Python is set up (conda or something else), the solution may vary. You might want to search the internet for the solution that works for you. For example: https://stackoverflow.com/questions/29846087/microsoft-visual-c-14-0-is-required-unable-to-find-vcvarsall-bat

**Comment by bsipocz** [comment]
@nden - I'm clueless, and suppose the best way forward is what @pllim suggested above.

**Comment by LucIJspeert** [comment]
After a few hours of looking around and trying fixes, I finally just reinstalled MSVC with a load of extra modules, and it worked... like magic. Problem is, now it seems to have broken my Photutils. Upon import I get:

```
Traceback (most recent call last):
File "<local_dir>\_test.py", line 3329, in <module>
    import photutils as phu
  File "<local_dir>\miniconda3\lib\site-packages\photutils\__init__.py", line 36, in <module>
    from .centroids import *  # noqa
  File "<local_dir>miniconda3\lib\site-packages\photutils\centroids\__init__.py", line 7, in <module>
    from .core import *    # noqa
  File "<local_dir>\miniconda3\lib\site-packages\photutils\centroids\core.py", line 25, in <module>
    class _GaussianConst1D(Const1D + Gaussian1D):
  File "<local_dir>\miniconda3\lib\site-packages\astropy\modeling\core.py", line 59, in <lambda>
    return lambda left, right: CompoundModel(oper, left, right, **kwargs)
  File "<local_dir>\miniconda3\lib\site-packages\astropy\modeling\core.py", line 2301, in __init__
    if len(left) != len(right):
TypeError: object of type '_ModelMeta' has no len()
```

I'm running version 0.6, should I also try installing the master branch of that one?

**Comment by nden** [comment]
@LucIJspeert I'm glad it worked eventually. One of the changes in the new modeling is that you can't combine classes any more, only instances of models (which is what triggers the above error). It was fixed in photutils master but nit released yet. You need to reinstall it from master.

**Comment by pllim** [comment]
@followthesheep , try using the dev version.

**Comment by nden** [comment]
@LucIJspeert Thanks for testing! 

@followthesheep I'm going to close this. If you run into similar or other problems please open a new issue.

**Comment by jaladh-singhal** [comment]
> @followthesheep It would be great if you can run your tests with the current astropy master and report if the memory issues are fixed

@nden Thanks alot for this fix, we recently tried this at [starkit](https://github.com/starkit) and found no memory leak. So right now, we added development version of astropy in our environment, eagerly looking forward for the release of v4.0.

Thanks to the entire astropy team for constantly bringing good work!

**Comment by nden** [comment]
@jaladh-singhal Thanks for the feedback!
