### ISSUE TITLE
sigma_clipped_stats: Use of numpy.nanfunctions incompatible with masked arrays

### ISSUE THREAD

**Issue by stscieisenhamer** [astropy/astropy#9973]
### Description

`astropy.stats.sigma_clipping.sigma_clipped_stats` may be inappropriately using `numpy.nanfunctions` when masked arrays are involved.

A typical issue that has arisen is spacetelescope/jwst#4451, where the error is

```
ValueError: output array is read-only
```

During investigation, a numpy issue, numpy/numpy#12283 was found which is directly related to the above issues. The discussion implies that the `numpy.lib.nanfunctions` are not intended to be used with masked arrays and is what is leading to the error situation.

This issue is intended to open up the discussion of whether `sigma_clipped_stats`, and any other functions that are using the `nanfunctions`, should switch to the standard, non-nan, functions when masked arrays are involved.

### Expected behavior

No error.

### Actual behavior

ValueError: output array is read-only

### Steps to Reproduce
Execute the following:

```python
from astropy.stats import sigma_clipped_stats
import numpy as np

arr = np.zeros(2)
sigma_clipped_stats(arr, mask_value=0.)
```

### System Details

macOS-10.13.6-x86_64-i386-64bit
Python 3.8.1 (default, Jan  8 2020, 16:15:59) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.18.1
astropy 4.0
Scipy 1.4.1

**Comment by jdavies-st** [comment]
If there is masking, it would probably be safe to use `np.mean` instead of `np.nanmean`, etc.  This has been broken since numpy 1.15 and doesn't look like it is close to being fixed, if ever.

**Comment by larrybradley** [comment]
@stscieisenhamer I don't get an error when I run your example (`astropy 4.0.1`, `numpy 1.18.2`):

```python
>>> from astropy.stats import sigma_clipped_stats
>>> import numpy as np
>>> arr = np.zeros(2)
>>> sigma_clipped_stats(arr, mask_value=0.)
(0.0, 0.0, 0.0)
```

Equivalently:
```python
>>> marr = np.ma.MaskedArray(arr, mask=True)
>>> sigma_clipped_stats(marr)
(0.0, 0.0, 0.0)
```

However, because the array is completely masked, it should probably return `(masked, masked, masked)`:

```python
>>> np.ma.mean(marr)
masked
>>> np.ma.median(marr)
masked
>>> np.ma.std(marr)
masked
```

**Comment by larrybradley** [comment]
I fixed `sigma_clipped_stats` to return `(masked, masked, masked)` in https://github.com/astropy/astropy/pull/10099.

**Comment by pllim** [comment]
Thanks, @larrybradley ! Can we close this then?

**Comment by jdavies-st** [comment]
@larrybradley I do still get the error with the latest `numpy 1.18.2` and `astropy 4.0.1`.

```
In [1]: from astropy.stats import sigma_clipped_stats
   ...: import numpy as np 
   ...:  
   ...: arr = np.zeros(2) 
   ...: sigma_clipped_stats(arr, mask_value=0.)                                                                                          
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-0182d4746293> in <module>
      3 
      4 arr = np.zeros(2)
----> 5 sigma_clipped_stats(arr, mask_value=0.)

~/miniconda3/envs/specutils/lib/python3.7/site-packages/astropy/stats/sigma_clipping.py in sigma_clipped_stats(data, mask, mask_value, sigma, sigma_lower, sigma_upper, maxiters, cenfunc, stdfunc, std_ddof, axis)
    754         std = _nanstd(data_clipped, ddof=std_ddof, axis=axis)
    755     else:  # pragma: no cover
--> 756         mean = np.nanmean(data_clipped, axis=axis)
    757         median = np.nanmedian(data_clipped, axis=axis)
    758         std = np.nanstd(data_clipped, ddof=std_ddof, axis=axis)

<__array_function__ internals> in nanmean(*args, **kwargs)

~/miniconda3/envs/specutils/lib/python3.7/site-packages/numpy/lib/nanfunctions.py in nanmean(a, axis, dtype, out, keepdims)
    950     cnt = np.sum(~mask, axis=axis, dtype=np.intp, keepdims=keepdims)
    951     tot = np.sum(arr, axis=axis, dtype=dtype, out=out, keepdims=keepdims)
--> 952     avg = _divide_by_count(tot, cnt, out=out)
    953 
    954     isbad = (cnt == 0)

~/miniconda3/envs/specutils/lib/python3.7/site-packages/numpy/lib/nanfunctions.py in _divide_by_count(a, b, out)
    212         if isinstance(a, np.ndarray):
    213             if out is None:
--> 214                 return np.divide(a, b, out=a, casting='unsafe')
    215             else:
    216                 return np.divide(a, b, out=out, casting='unsafe')

ValueError: output array is read-only

In [2]: np.__version__
Out[2]: '1.18.2'

In [3]: import astropy

In [4]: astropy.__version__
Out[4]: '4.0.1'
```

**Comment by pllim** [comment]
@jdavies-st , please try the dev version.
